---
- name: Check if pyenv is installed
  ansible.builtin.command: which pyenv
  register: pyenv_which
  changed_when: false
  failed_when: false

- name: Install pyenv
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv/bin/pyenv"
  when: pyenv_which.rc != 0
