---
snap_packages:
  # Development tools
  - { name: code, classic: true }
  - { name: dbeaver-ce, classic: true }
  - { name: glab, classic: false }
  - { name: redisinsight, classic: false }

  # Browsers and communication
  - { name: bitwarden, classic: false }
  - { name: discord, classic: false }
  - { name: firefox, classic: false }
  - { name: telegram-desktop, classic: false }
  - { name: thunderbird, classic: false }

  # Productivity and media
  - { name: figma-linux, classic: false }
  - { name: onlyoffice-desktopeditors, classic: false }
  - { name: organize-my-files, classic: false }
  - { name: spotify, classic: false }
  - { name: steam, classic: false }

  # Games
  - { name: 0ad, classic: false }
