---
- name: Ensure snapd is installed and running
  ansible.builtin.apt:
    name: snapd
    state: present

- name: Wait for snapd seeding to complete
  ansible.builtin.command: snap wait system seed.loaded
  changed_when: false

- name: Install snaps
  ansible.builtin.command: >
    snap install {{ item.name }}
    {% if item.classic | default(false) %}--classic{% endif %}
    {% if item.channel | default('stable') != 'stable' %}--channel={{ item.channel }}{% endif %}
  args:
    creates: "/snap/{{ item.name }}/current"
  loop: "{{ snap_packages }}"
  register: snap_install_result
  retries: 3
  delay: 10
  until: snap_install_result is succeeded
